// Trading day utilities

export const NSE_SYMBOLS = [
  "ADANIENT.NS",
  "ADANIPORTS.NS",
  "APOLLOHOSP.NS",
  "ASIANPAINT.NS",
  "AXISBANK.NS",
  "BAJAJ-AUTO.NS",
  "BAJAJFINSV.NS",
  "BAJFINANCE.NS",
  "BEL.NS",
  "BHARTIARTL.NS",
  "CIPLA.NS",
  "COALINDIA.NS",
  "DRREDDY.NS",
  "EICHERMOT.NS",
  "GRASIM.NS",
  "HCLTECH.NS",
  "HDFCBANK.NS",
  "HDFCLIFE.NS",
  "HINDALCO.NS",
  "HINDUNILVR.NS",
  "ICICIBANK.NS",
  "INDIGO.NS",
  "INFY.NS",
  "ITC.NS",
  "JIOFIN.NS",
  "JSWSTEEL.NS",
  "KOTAKBANK.NS",
  "LT.NS",
  "M&M.NS",
  "MARUTI.NS",
  "NESTLEIND.NS",
  "NTPC.NS",
  "ONGC.NS",
  "POWERGRID.NS",
  "RELIANCE.NS",
  "SBILIFE.NS",
  "SBIN.NS",
  "SHRIRAMFIN.NS",
  "SUNPHARMA.NS",
  "TATACONSUM.NS",
  "TATASTEEL.NS",
  "TCS.NS",
  "TECHM.NS",
  "TITAN.NS",
  "TRENT.NS",
  "ULTRACEMCO.NS",
  "WIPRO.NS",
  "ABB.NS",
  "AMBUJACEM.NS",
  "BANKBARODA.NS",
  "BERGEPAINT.NS",
  "BOSCHLTD.NS",
  "CANBK.NS",
  "CHOLAFIN.NS",
  "COLPAL.NS",
  "DABUR.NS",
  "DLF.NS",
  "GODREJCP.NS",
  "HAVELLS.NS",
  "HEROMOTOCO.NS",
  "ICICIPRULI.NS",
  "IDFCFIRSTB.NS",
  "INDHOTEL.NS",
  "IOC.NS",
  "IRCTC.NS",
  "JINDALSTEL.NS",
  "LICI.NS",
  "LUPIN.NS",
  "MARICO.NS",
  "MOTHERSON.NS",
  "NAUKRI.NS",
  "PEL.NS",
  "PERSISTENT.NS",
  "PIDILITIND.NS",
  "PNB.NS",
  "POLYCAB.NS",
  "SIEMENS.NS",
  "SRF.NS",
  "TORNTPHARM.NS",
  "TVSMOTOR.NS",
  "UNIONBANK.NS",
  "UNITDSPR.NS",
  "VBL.NS",
  "VEDL.NS",
  "ZOMATO.NS",
  "ZYDUSLIFE.NS",
];

export const COMPANY_NAMES: Record<string, string> = {
  "ADANIENT.NS": "Adani Enterprises",
  "ADANIPORTS.NS": "Adani Ports",
  "APOLLOHOSP.NS": "Apollo Hospitals",
  "ASIANPAINT.NS": "Asian Paints",
  "AXISBANK.NS": "Axis Bank",
  "BAJAJ-AUTO.NS": "Bajaj Auto",
  "BAJAJFINSV.NS": "Bajaj Finserv",
  "BAJFINANCE.NS": "Bajaj Finance",
  "BEL.NS": "Bharat Electronics",
  "BHARTIARTL.NS": "Bharti Airtel",
  "CIPLA.NS": "Cipla",
  "COALINDIA.NS": "Coal India",
  "DRREDDY.NS": "Dr. Reddys Labs",
  "EICHERMOT.NS": "Eicher Motors",
  "GRASIM.NS": "Grasim Industries",
  "HCLTECH.NS": "HCL Technologies",
  "HDFCBANK.NS": "HDFC Bank",
  "HDFCLIFE.NS": "HDFC Life",
  "HINDALCO.NS": "Hindalco Industries",
  "HINDUNILVR.NS": "Hindustan Unilever",
  "ICICIBANK.NS": "ICICI Bank",
  "INDIGO.NS": "IndiGo (InterGlobe)",
  "INFY.NS": "Infosys",
  "ITC.NS": "ITC",
  "JIOFIN.NS": "Jio Financial Services",
  "JSWSTEEL.NS": "JSW Steel",
  "KOTAKBANK.NS": "Kotak Mahindra Bank",
  "LT.NS": "Larsen & Toubro",
  "M&M.NS": "Mahindra & Mahindra",
  "MARUTI.NS": "Maruti Suzuki",
  "NESTLEIND.NS": "Nestle India",
  "NTPC.NS": "NTPC",
  "ONGC.NS": "ONGC",
  "POWERGRID.NS": "Power Grid Corp",
  "RELIANCE.NS": "Reliance Industries",
  "SBILIFE.NS": "SBI Life Insurance",
  "SBIN.NS": "State Bank of India",
  "SHRIRAMFIN.NS": "Shriram Finance",
  "SUNPHARMA.NS": "Sun Pharma",
  "TATACONSUM.NS": "Tata Consumer Products",
  "TATASTEEL.NS": "Tata Steel",
  "TCS.NS": "Tata Consultancy Services",
  "TECHM.NS": "Tech Mahindra",
  "TITAN.NS": "Titan Company",
  "TRENT.NS": "Trent",
  "ULTRACEMCO.NS": "UltraTech Cement",
  "WIPRO.NS": "Wipro",
  "ABB.NS": "ABB India",
  "AMBUJACEM.NS": "Ambuja Cements",
  "BANKBARODA.NS": "Bank of Baroda",
  "BERGEPAINT.NS": "Berger Paints",
  "BOSCHLTD.NS": "Bosch",
  "CANBK.NS": "Canara Bank",
  "CHOLAFIN.NS": "Chola Finance",
  "COLPAL.NS": "Colgate-Palmolive",
  "DABUR.NS": "Dabur India",
  "DLF.NS": "DLF",
  "GODREJCP.NS": "Godrej Consumer Products",
  "HAVELLS.NS": "Havells India",
  "HEROMOTOCO.NS": "Hero MotoCorp",
  "ICICIPRULI.NS": "ICICI Prudential Life",
  "IDFCFIRSTB.NS": "IDFC First Bank",
  "INDHOTEL.NS": "Indian Hotels",
  "IOC.NS": "Indian Oil Corp",
  "IRCTC.NS": "IRCTC",
  "JINDALSTEL.NS": "Jindal Steel & Power",
  "LICI.NS": "LIC Of India",
  "LUPIN.NS": "Lupin",
  "MARICO.NS": "Marico",
  "MOTHERSON.NS": "Samvardhana Motherson",
  "NAUKRI.NS": "Info Edge (Naukri)",
  "PEL.NS": "Piramal Enterprises",
  "PERSISTENT.NS": "Persistent Systems",
  "PIDILITIND.NS": "Pidilite Industries",
  "PNB.NS": "Punjab National Bank",
  "POLYCAB.NS": "Polycab India",
  "SIEMENS.NS": "Siemens India",
  "SRF.NS": "SRF",
  "TORNTPHARM.NS": "Torrent Pharma",
  "TVSMOTOR.NS": "TVS Motor Company",
  "UNIONBANK.NS": "Union Bank of India",
  "UNITDSPR.NS": "United Spirits",
  "VBL.NS": "Varun Beverages",
  "VEDL.NS": "Vedanta",
  "ZOMATO.NS": "Zomato",
  "ZYDUSLIFE.NS": "Zydus Lifesciences",
};

export const SECTOR_MAP: Record<string, string> = {
  "ADANIENT.NS": "Energy",
  "ADANIPORTS.NS": "Infrastructure",
  "APOLLOHOSP.NS": "Healthcare",
  "ASIANPAINT.NS": "Consumer",
  "AXISBANK.NS": "Financial Services",
  "BAJAJ-AUTO.NS": "Automobile",
  "BAJAJFINSV.NS": "Financial Services",
  "BAJFINANCE.NS": "Financial Services",
  "BEL.NS": "Defence",
  "BHARTIARTL.NS": "Telecom",
  "CIPLA.NS": "Healthcare",
  "COALINDIA.NS": "Energy",
  "DRREDDY.NS": "Healthcare",
  "EICHERMOT.NS": "Automobile",
  "GRASIM.NS": "Materials",
  "HCLTECH.NS": "IT",
  "HDFCBANK.NS": "Financial Services",
  "HDFCLIFE.NS": "Financial Services",
  "HINDALCO.NS": "Metals",
  "HINDUNILVR.NS": "FMCG",
  "ICICIBANK.NS": "Financial Services",
  "INDIGO.NS": "Aviation",
  "INFY.NS": "IT",
  "ITC.NS": "FMCG",
  "JIOFIN.NS": "Financial Services",
  "JSWSTEEL.NS": "Metals",
  "KOTAKBANK.NS": "Financial Services",
  "LT.NS": "Infrastructure",
  "M&M.NS": "Automobile",
  "MARUTI.NS": "Automobile",
  "NESTLEIND.NS": "FMCG",
  "NTPC.NS": "Energy",
  "ONGC.NS": "Energy",
  "POWERGRID.NS": "Energy",
  "RELIANCE.NS": "Energy",
  "SBILIFE.NS": "Financial Services",
  "SBIN.NS": "Financial Services",
  "SHRIRAMFIN.NS": "Financial Services",
  "SUNPHARMA.NS": "Healthcare",
  "TATACONSUM.NS": "FMCG",
  "TATASTEEL.NS": "Metals",
  "TCS.NS": "IT",
  "TECHM.NS": "IT",
  "TITAN.NS": "Consumer",
  "TRENT.NS": "Consumer",
  "ULTRACEMCO.NS": "Cement",
  "WIPRO.NS": "IT",
  "ABB.NS": "Industrials",
  "AMBUJACEM.NS": "Cement",
  "BANKBARODA.NS": "Financial Services",
  "BERGEPAINT.NS": "Consumer",
  "BOSCHLTD.NS": "Automobile",
  "CANBK.NS": "Financial Services",
  "CHOLAFIN.NS": "Financial Services",
  "COLPAL.NS": "FMCG",
  "DABUR.NS": "FMCG",
  "DLF.NS": "Real Estate",
  "GODREJCP.NS": "FMCG",
  "HAVELLS.NS": "Consumer",
  "HEROMOTOCO.NS": "Automobile",
  "ICICIPRULI.NS": "Financial Services",
  "IDFCFIRSTB.NS": "Financial Services",
  "INDHOTEL.NS": "Consumer",
  "IOC.NS": "Energy",
  "IRCTC.NS": "Consumer",
  "JINDALSTEL.NS": "Metals",
  "LICI.NS": "Financial Services",
  "LUPIN.NS": "Healthcare",
  "MARICO.NS": "FMCG",
  "MOTHERSON.NS": "Automobile",
  "NAUKRI.NS": "IT",
  "PEL.NS": "Healthcare",
  "PERSISTENT.NS": "IT",
  "PIDILITIND.NS": "Materials",
  "PNB.NS": "Financial Services",
  "POLYCAB.NS": "Industrials",
  "SIEMENS.NS": "Industrials",
  "SRF.NS": "Materials",
  "TORNTPHARM.NS": "Healthcare",
  "TVSMOTOR.NS": "Automobile",
  "UNIONBANK.NS": "Financial Services",
  "UNITDSPR.NS": "FMCG",
  "VBL.NS": "FMCG",
  "VEDL.NS": "Metals",
  "ZOMATO.NS": "Consumer",
  "ZYDUSLIFE.NS": "Healthcare",
};

// Get next N trading days from today
export function getNextTradingDays(n = 10): Date[] {
  const days: Date[] = [];
  const d = new Date();
  while (days.length < n) {
    d.setDate(d.getDate() + 1);
    const dow = d.getDay();
    if (dow !== 0 && dow !== 6) {
      days.push(new Date(d));
    }
  }
  return days;
}

// Format date for display
export function formatTradingDate(d: Date): string {
  return d.toLocaleDateString("en-IN", {
    timeZone: "Asia/Kolkata",
    weekday: "short",
    day: "2-digit",
    month: "short",
  });
}

// Map horizon number to approximate date
export function horizonToDate(horizonDays: number): Date {
  const [nextDay, ...rest] = getNextTradingDays(horizonDays);
  return rest.length > 0 ? rest[rest.length - 1] : nextDay;
}

// Calculate signal bias ratio
export function signalBiasRatio(long: number, short: number): number {
  const total = long + short;
  return total > 0 ? long / total : 0.5;
}
